### ISSUE TITLE
Convert Ben's Scripts

### ISSUE THREAD

**Issue by stitova-idm** [InstituteforDiseaseModeling/emodpy-snt#24]
@ZDu-IDM, please list them here

**Comment by ZDu-IDM** [comment]
- [ ] Convert Ben's analyzers #25
- [ ] Convert Ben's Python Examples #26
- [ ] Convert Ben's HBHI Library #27

**Comment by stitova-idm** [comment]
Implemented and tested.
